

apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: generator
policyDefaults:
  namespace: wookie-policies
  remediationAction: enforce
  placement:
    placementRuleName: dev
policies:
  - name: argo-oper
    remediationAction: enforce
    manifests:
      - path: namespace.yml

